### ISSUE TITLE
Add video wrapper and map wrapper classes

### ISSUE THREAD

**Issue by Dcaff206** [tributemedia/tribute#9]
add the css for .video-wrapper  and .map-wrapper to main.css

HTML

<div class="video-wrapper"><iframe allowfullscreen="" frameborder="0" height="315" src="###" width="560"></iframe></div>

CSS

.video-wrapper, .map-wrapper {
	position: relative;
	padding-bottom: 56.25%; /* 16:9 */
	padding-top: 25px;
	height: 0;
}

.video-wrapper iframe, .map-wrapper iframe {
	position: absolute;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
}

**Comment by AntonioXIII** [comment]
Merged into dev, and ready for release.
